apiVersion: v1
kind: Service
metadata:
  name: my-prj-svc
  labels:
    app: my-prj
spec:
  selector:
    app: my-prj
    tier: backend
  ports:
    - protocol: TCP
      port: 11000
      targetPort: 11000
  type: LoadBalancer